name: LinkedIn Job Scraper

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 15 * * *'

jobs:
  scrape:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Download IEDriverServer
      run: |
        Invoke-WebRequest -Uri https://selenium-release.storage.googleapis.com/3.150/IEDriverServer_Win32_3.150.1.zip -OutFile IEDriverServer.zip
        Expand-Archive -Path IEDriverServer.zip -DestinationPath .
        $env:PATH += ";$pwd\IEDriverServer"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium requests beautifulsoup4 schedule

    - name: Run scraper
      env:
        LINKEDIN_USERNAME: ${{ secrets.LINKEDIN_USERNAME }}
        LINKEDIN_PASSWORD: ${{ secrets.LINKEDIN_PASSWORD }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      run: |
        python main.py
